### ISSUE TITLE
查询人物无法显示全部

### ISSUE THREAD

**Issue by davidelectricfree** [Arondight/Adachi-BOT#437] opened 2021-11-25 04:31 UTC
![2148b2852cc84fa0.jpg](https://user-images.githubusercontent.com/36690822/143379862-3f042e97-3cd0-498f-aa5b-51712e2216a2.jpg)
深渊似乎也看不全了

**Comment by Mark9804** [comment] 2021-11-25 04:31
Duplicate of #436

**Closed** 2021-11-25 04:36 UTC
Labels: duplicate
